Change default site url
canonical/indico-operator pull request #142
Opened 2022-09-27 16:13 UTC by arturo-seijas

Ddd the suffix `.local` to the default site URL. It will now be [application name].local

2022-09-27 16:14 UTC, mthaddon requested changes
Can we update the README as well pls?

2022-09-27 16:16 UTC, arturo-seijas commented
> Can we update the README as well pls?

Done

2022-09-27 16:17 UTC, mthaddon reviewed
One other small update needed

2022-09-27 16:17 UTC, mthaddon commented on README.md
>  a browser (assuming `indico` resolves to the IP(s) of your k8s ingress)
"assuming `indico.local` resolves"

2022-09-28 03:55 UTC, jdkandersson requested changes

2022-09-28 03:55 UTC, jdkandersson commented on src/charm.py
> +        return urlparse(site_url).hostname if site_url else "{}.local".format(self.app.name)
Should this be an f-string?

2022-09-28 07:30 UTC, arturo-seijas commented on README.md
>  a browser (assuming `indico` resolves to the IP(s) of your k8s ingress)
Thanks

2022-09-28 07:30 UTC, arturo-seijas commented on src/charm.py
> +        return urlparse(site_url).hostname if site_url else "{}.local".format(self.app.name)
Yes

2022-09-28 08:35 UTC, mthaddon commented on src/charm.py
> +                "Invalid saml_target_url option provided. Only {UBUNTU_SAML_URL} is available."
Does this need an "f" prefix?

2022-09-28 09:02 UTC, mthaddon approved these changes
LGTM, thx

2022-09-28 09:24 UTC, merkata approved these changes
Very nice, approving.

2022-09-28 11:49 UTC, merged