Refactor workflow logic
canonical/indico-operator pull request #150
Opened 2022-10-07 11:17 UTC by arturo-seijas

This PR refactors the test and comment workflows to better align with the next steps: extracting the comment functionality to and action and create reusable workflows.
As part of this PR the promote charm workflow is also improved, giving it a more user friendly name and drowdowns instead of text boxes to select the origin and destination channels.

2022-10-07 11:39 UTC, merkata submitted a review, later dismissed
Awesome changes, really clear and the refactoring improves readability (and re-usability)! Approving.

2022-10-10 01:25 UTC, weiiwang01 requested changes

2022-10-10 01:25 UTC, weiiwang01 commented on .github/files/extract_test_result.py
> +            f"```{no_color(lint_output).strip()}\n```"
A newline is needed immediately after the first triple backticks.
This applies to some following reports too.

```
            f"```\n{no_color(lint_output).strip()}\n```"
```

2022-10-10 04:37 UTC, jdkandersson requested changes

2022-10-10 04:37 UTC, jdkandersson commented on tox.ini
> +[testenv:static]
I think I saw this in another PR and might not have had a chance to comment there, what is the difference between `static` and `lint`? `bandit` seems to be another linting tool, is it worth just including it in the lint output rather than as a separate command?

2022-10-10 07:52 UTC, arturo-seijas commented on .github/files/extract_test_result.py
> +            f"```{no_color(lint_output).strip()}\n```"
Done

2022-10-10 07:57 UTC, arturo-seijas commented on tox.ini
> +[testenv:static]
As I see it, linting could be considered a part of the static analysis. We could merge both targets, but I don't see a strong driver for that.

2022-10-10 07:59 UTC, weiiwang01 approved these changes

2022-10-10 08:18 UTC, arturo-seijas commented
Closed as #146 prevents actions from forks to succeed

2022-10-10 08:18 UTC, closed without merging