ISD-207 reusable GitHub ci test stage
canonical/indico-operator pull request #152
Opened 2022-10-10 09:25 UTC by arturo-seijas

2022-10-11 08:48 UTC, mthaddon commented on .github/workflows/integration_test.yaml
> +        run: echo "::set-output name=images::$(ls *.Dockerfile | sed s/\.Dockerfile// |  jq -Rsc '. / "\n" - [""]')"
This will error if there are no files matching in the root directory of the charm. This is the case for nginx-ingress-integrator (which has no workload defined), as well as discourse-k8s (which defines its Dockerfile in the `image` folder). Is there a way of dealing with those cases?

2022-10-11 08:50 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +          image_names=$(echo '${{ needs.get-images.outputs.images }}' | jq -c '.[]' | sed 's/\"//g')
You can use "jq -cr" and the output will be without double-quote, so you can remove the sed
```suggestion
          image_names=$(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]')
```

2022-10-11 08:58 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +        run: echo "::set-output name=images::$(ls *.Dockerfile | sed s/\.Dockerfile// |  jq -Rsc '. / "\n" - [""]')"
Fixed. Thank you. I hadn't considered that scenario

2022-10-11 10:10 UTC, weiiwang01 submitted a review, later dismissed
LGTM, thanks!

2022-10-11 10:12 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +  build-images:
As mentioned in the comment of Tom, would be interesting to skip this job if there are no dockerfile

2022-10-11 10:43 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +  build-images:
The current approach will output an empty JSON array that is needed for the input matrix in order not to fail. This looks simpler to me.

2022-10-11 11:39 UTC, mthaddon commented on .github/workflows/integration_test.yaml
> +  build-images:
what about the case where the files are in sub-folders? This will simply ignore these currently, do we just make it a requirement that the Dockerfile is in the main directory, and follows this naming convention?

2022-10-11 11:46 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +  build-images:
I'd go for a "convention over configuration" approach.We can also a subfolder for the dockerfiles right now if you think that'd be more appropriate.

2022-10-11 14:05 UTC, mthaddon commented on .github/workflows/integration_test.yaml
> +  build-images:
I'm not sure we do want to standardise on having dockerfiles in the top level directory of the project named `${container-name}.Dockerfile` as an `ls` for instance wouldn't group all the dockerfiles together (I realise this is a bit pedantic, but that is the first thing that sprung to mind when looking at this naming convention). If it is possible to look for subdirectories and do the right thing (I assume build with a context of the directory we find the Dockerfile in?) I think it might be worth the extra effort at this stage.

2022-10-11 14:32 UTC, mthaddon commented on .github/workflows/integration_test.yaml
> +  build-images:
We already have two charms that work this way (dockerfiles not in the root directory) - discourse-k8s and gunicorn-k8s. So I think it's worth having a solution that will work for them. I agree simplicity is good, I'm just not sure `${container-name}.Dockerfile` in the root directory is the right approach.

2022-10-11 14:40 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +  build-images:
In the case of gunicorn the build context is root; for discourse, it is the directory in which the image is placed. We can scan images regardless of their location (although it will be more complex) but we'll need to decide which will be the build context for those cases and adapt the charms accordingly.

2022-10-11 16:17 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +  build-images:
Sorry to insist but skipped jobs are shown but as "skipped"
Like:
![image](https://user-images.githubusercontent.com/114007538/195145217-21f0a7f9-ca65-484d-a60d-c6afa9eec930.png)

And unfortunately it seems the job will fail if the get-images return an empty array see:
https://github.com/orgs/community/discussions/27096

So I strongly suggest to add the `if` statement

2022-10-12 00:58 UTC, jdkandersson requested changes

2022-10-12 00:58 UTC, jdkandersson commented on .github/workflows/integration_test.yaml
> +        run: echo "::set-output name=images::$(ls *.Dockerfile 2> /dev/null | sed s/\.Dockerfile// |  jq -Rsc '. / "\n" - [""]')"
I'm not sure if the following is possible, could we include the name of the image in the output? E.g., indico? This might make it easier to read the workflow since you would know exactly which image is being accessed rather than having to check based on the index in an array or something like that

2022-10-12 00:58 UTC, jdkandersson commented on .github/workflows/integration_test.yaml
> +          image_names=$(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]')
Could it be worth formatting the output such that further processing isn't required? It would simplify this a bit

2022-10-12 07:35 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +  build-images:
@gregory-schiano , it does indeed fail. I added that ìf ` and an `if always()` condition on the next job to properly handle empty values returned by the first step

2022-10-12 07:37 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +        run: echo "::set-output name=images::$(ls *.Dockerfile 2> /dev/null | sed s/\.Dockerfile// |  jq -Rsc '. / "\n" - [""]')"
We have visibility in the next step. Does that work for you?
![image](https://user-images.githubusercontent.com/102022572/195279852-6ca9cb4a-edb6-4645-a7c5-4af8ca1f2211.png)

2022-10-12 08:07 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +          image_names=$(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]')
Not sure it's possible github actions enforce the output format as json while bash can't iterate on json array directly
But we can directly iterate in the for loop from the output of JQ (prehaps less readable)
```suggestion
          for image_name in $(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]'); do
```

2022-10-12 08:07 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +  build-images:
Thanks, good catch for the "always()" didn't think about the next job

2022-10-12 08:21 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +          image_names=$(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]')
The best I could do is:
```
args=$(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]' | \
            xargs -I{} echo "--${image_name}-image ${{ env.REGISTRY }}/${{ env.OWNER }}/${image_name}:${{ github.run_id }}" | \
            paste -sd' ' -
```
Any suggestions?

2022-10-12 11:50 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +          image_names=$(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]')
I think the for loop is more readable than the xargs / paste

2022-10-12 11:52 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +          image_names=$(echo '${{ needs.get-images.outputs.images }}' | jq -cr '.[]')
Agreed

2022-10-13 02:18 UTC, jdkandersson approved these changes, later dismissed

2022-10-13 11:39 UTC, weiiwang01 approved these changes
LGTM, thanks!

2022-10-13 11:50 UTC, merkata approved these changes
Significantly reduced and improved readability, awesome! Approving.

2022-10-13 12:05 UTC, gregory-schiano commented on .github/workflows/publish_charm.yaml
> +          charmcraft upload-resource $charmName ${{ matrix.image }}-image --image=$imageId --verbosity=trace
Is verbosity trace needed ? Could lead to too much output ?

2022-10-13 12:10 UTC, merged

2022-10-13 12:13 UTC, arturo-seijas commented on .github/workflows/publish_charm.yaml
> +          charmcraft upload-resource $charmName ${{ matrix.image }}-image --image=$imageId --verbosity=trace
The upload is a little flaky sometimes. That's why it's in place. Hoepfully this will go away when migrating charmhub to PS5