ISD-203 indico export uwsgi metrics to prometheus
canonical/indico-operator pull request #153
Opened 2022-10-11 14:01 UTC by merkata

This PR configures the uwsgi component of Indico to send statsd statistics and adds a statsd prometheus exporter to consume them and make them available for scraping by prometheus. Unit and integration tests are modified to reflect that as well.

2022-10-11 14:08 UTC, arturo-seijas commented on files/etc/indico/uwsgi.ini
> +stats-push = statsd:127.0.0.1:9125
Will this publish the metrics in a statsd server in the same container?

2022-10-11 14:19 UTC, arturo-seijas commented on files/etc/indico/uwsgi.ini
> +stats-push = statsd:127.0.0.1:9125
Following some kind of architectural IoC pattern, we should ideally let prometheus scrape them (although the other approach is also possible but it’s really aimed for workloads such as cronjobs, that can’t expose an endpoint permanently):

Prometheus will scrape the target exposed by the prometheus-statsd exporter

Prometheus statsd exported should scrape the uwsgi statsd target

2022-10-11 15:19 UTC, arturo-seijas commented on files/etc/indico/uwsgi.ini
> +stats-push = statsd:127.0.0.1:9125
Nvm, apparently this is not supported by the exporter

2022-10-12 02:18 UTC, jdkandersson requested changes

2022-10-12 02:18 UTC, jdkandersson commented on src/charm.py
> +        """Generate pebble config for the statsd-prometheus-exporter container."""
We have a coding standard for docstrings which includes describing return values, do you think it is applicable here? https://github.com/canonical/is-charms-contributing-guide/blob/main/CONTRIBUTING.md#docstrings

2022-10-12 02:18 UTC, jdkandersson commented on tests/integration/test_charm.py
> +    """Check that the prometheus exporters are up and running.
We have a standard for describing tests, do you think it is applicable here? https://github.com/canonical/is-charms-contributing-guide/blob/main/CONTRIBUTING.md#test-structure

2022-10-12 04:53 UTC, merkata commented on src/charm.py
> +        """Generate pebble config for the statsd-prometheus-exporter container."""
I wasn't sure, as I copied the `_get_nginx_prometheus_exporter_pebble_config` and modified it to my needs, and it didn't have our standard (and at that point no function has it). I can use the standard for the new functions and the old ones can be refactored in an additional story, I think that would be fine - would do you think?

2022-10-12 04:53 UTC, merkata commented on tests/integration/test_charm.py
> +    """Check that the prometheus exporters are up and running.
Same as above.

2022-10-12 04:54 UTC, jdkandersson commented on src/charm.py
> +        """Generate pebble config for the statsd-prometheus-exporter container."""
Yes, that is also in line with our other standard for non-compliant code 😉 https://github.com/canonical/is-charms-contributing-guide/blob/main/CONTRIBUTING.md#non-compliant-code

2022-10-12 05:04 UTC, merkata commented on src/charm.py
> +        """Generate pebble config for the statsd-prometheus-exporter container."""
Yes, I remember discussing it - thanks for the pointer, I'm adding this now! :)

2022-10-12 05:34 UTC, jdkandersson submitted a review, later dismissed
Nice!

2022-10-13 00:15 UTC, jdkandersson submitted a review, later dismissed

2022-10-13 13:10 UTC, arturo-seijas approved these changes
LGTM

2022-10-13 13:12 UTC, gtrkiller approved these changes
LGTM

2022-10-13 13:21 UTC, merged