Ldap support
canonical/indico-operator pull request #187
Opened 2022-11-25 16:25 UTC by arturo-seijas

2023-01-17 23:49 UTC, jdkandersson submitted a review, later dismissed

2023-01-18 06:48 UTC, mthaddon commented on src/charm.py
> +                            "phone": "mobile",
Are we really planning to sync phone numbers? Is that required by Indico somehow? Seems potentially problematic or unexpected.

2023-01-18 06:48 UTC, mthaddon commented on src/charm.py
> +                _ldap_config = {
It seems odd that we're pulling some variables here (`ldap_host`) and hard coding others (`cn=Indico Bot,ou=bots,dc=canonical,dc=com`). I realise we're only supporting one provider currently, but surely this should be checking if the host matches what we're expecting and mapping values to that? Maybe just `if self.config["ldap_host"] == "ldap.canonical.com"`?

2023-01-18 06:48 UTC, mthaddon commented on .github/workflows/integration_test.yaml
> +      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
Is this intended, seems unrelated?

2023-01-18 06:48 UTC, mthaddon commented on config.yaml
> +    description: LDAP for the LDAP server to use as identity provider.
This description doesn't quite make sense. Can you reword it?

2023-01-18 08:24 UTC, arturo-seijas commented on src/charm.py
> +                _ldap_config = {
Not sure I follow. I see only two variable in that block: ldap_host and ldap_password

2023-01-18 08:25 UTC, arturo-seijas commented on config.yaml
> +    description: LDAP for the LDAP server to use as identity provider.
Done

2023-01-18 08:26 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
It is, we have some checks failing because of that, though we will probably remove this check on PR submission

2023-01-18 08:41 UTC, gregory-schiano commented on config.yaml
> +    description: URL for the LDAP server to use as identity provider. Requires SAML to be configured.
Is it and URI or a host ?
If that's an URI I'd call it `ldap_uri`

2023-01-18 08:41 UTC, gregory-schiano commented on config.yaml
> +    description: LDAP for the LDAP server to use as identity provider.
Yeap he probably meant `Password for the LDAP server`

2023-01-18 08:41 UTC, gregory-schiano commented on indico.Dockerfile
> +    && chown indico:indico /srv/indico  /srv/indico/cache /srv/indico/archive /srv/indico/custom \
Why not using the {} as in the previous command here ?

2023-01-18 08:41 UTC, gregory-schiano commented on src/charm.py
> +        return [item.split("|")[1].strip() for item in output.split("\n")[3:-2]]
Did you test with no plugins installed ?

P.S.: Ah I see this was pre-existing code, but could worth it checking this edge case

2023-01-18 08:41 UTC, gregory-schiano commented on src/charm.py
> +                _ldap_config = {
This charm is not "Canonical" only, so indeed these variables shouldn't be hardcoded as it'll make it unusable for other users.
Usually on application providing LDAP connection provides at least the following configuration params:
- bind DN
- user DN
- user filter
- group DN
- group filter
- And fields to fetch for username, email, id, group_name, ...

2023-01-18 08:41 UTC, gregory-schiano commented on src/charm.py
> +                    "ubuntu_ldap": {
I'd make this naming generic like "ldap_provider"

2023-01-18 08:41 UTC, gregory-schiano commented on src/charm.py
> +                    "ubuntu": {
I'd make this name generic like `provider`

2023-01-18 08:41 UTC, gregory-schiano commented on src/charm.py
> +            return
Why limiting to Canonical LDAP only ?

2023-01-18 08:45 UTC, nrobinaubertin requested changes

2023-01-18 08:45 UTC, nrobinaubertin commented on indico.Dockerfile
> +RUN python3 -m pip install --no-cache-dir --prefer-binary indico==3.2 indico-plugin-piwik indico-plugin-storage-s3 python-ldap python3-saml uwsgi
I'm not completely sure, but I thought that to install to `$HOME/.local`, you needed to add `--user` to the `pip install` command

2023-01-18 08:45 UTC, nrobinaubertin commented on src/charm.py
>          return f"redis://{broker_host}:{broker_port}"
Since this function is for redis cache and broker, I would avoid using the words broker and cache (and replace them by just "redis")

2023-01-18 09:10 UTC, arturo-seijas commented on config.yaml
> +    description: URL for the LDAP server to use as identity provider. Requires SAML to be configured.
Host, not URI `"uri": f"ldaps://{self.config['ldap_host']}"`

2023-01-18 09:17 UTC, arturo-seijas commented on src/charm.py
> +            return
It would be quite complex to pass all these configs, so that's the scope for now, same as for SAML

2023-01-18 09:17 UTC, arturo-seijas commented on src/charm.py
> +                    "ubuntu_ldap": {
It won't be reusable anyway

2023-01-18 09:17 UTC, arturo-seijas commented on src/charm.py
> +                    "ubuntu": {
It won't be reusable anyway

2023-01-18 09:20 UTC, arturo-seijas commented on indico.Dockerfile
> +RUN python3 -m pip install --no-cache-dir --prefer-binary indico==3.2 indico-plugin-piwik indico-plugin-storage-s3 python-ldap python3-saml uwsgi
Running as the user also does the trick

2023-01-18 09:20 UTC, arturo-seijas commented on src/charm.py
>          return f"redis://{broker_host}:{broker_port}"
Indeed. Fixed

2023-01-18 09:23 UTC, arturo-seijas commented on src/charm.py
> +                _ldap_config = {
It would be quite complex to pass all these configs, so that's the scope for now, same as for SAML

2023-01-18 09:25 UTC, mthaddon commented on src/charm.py
> +                            "phone": "mobile",
Yes please, let's remove it.

2023-01-18 09:27 UTC, arturo-seijas commented on src/charm.py
> +                            "phone": "mobile",
Done

2023-01-18 09:28 UTC, arturo-seijas commented on indico.Dockerfile
> +    && chown indico:indico /srv/indico  /srv/indico/cache /srv/indico/archive /srv/indico/custom \
Indeed. Changed

2023-01-18 09:30 UTC, mthaddon commented on src/charm.py
> +                _ldap_config = {
I agree we should try to avoid having to specify all those values in juju config if possible, and I think the approach of only requiring ldap_host and ldap_password makes sense, but my comment was about the fact that we're checking `if self.config["ldap_host"] but then defining `_ldap_config` to include some hard coded and some parameterised values. If we add support for other LDAP providers in the future (or if someone like me is reading through the code) it might be a bit confusing.

2023-01-18 09:30 UTC, nrobinaubertin submitted a review, later dismissed
LGTM

2023-01-18 12:08 UTC, arturo-seijas commented on src/charm.py
> +                    "ubuntu_ldap": {
Done

2023-01-18 12:09 UTC, arturo-seijas commented on src/charm.py
> +                    "ubuntu": {
Done

2023-01-18 13:43 UTC, arturo-seijas commented on src/charm.py
> +                _ldap_config = {
Changed

2023-01-18 13:52 UTC, amandahla commented on src/charm.py
> +CANONICAL_LDAP_HOST = "ldap.canonical.com"
alphabetical order?

2023-01-18 13:54 UTC, amandahla commented on src/charm.py
> +        """Check if the LDAP hostis currently supported."""
Minor thing: host is

2023-01-18 13:58 UTC, arturo-seijas commented on src/charm.py
> +CANONICAL_LDAP_HOST = "ldap.canonical.com"
Fixed

2023-01-18 13:59 UTC, arturo-seijas commented on src/charm.py
> +        """Check if the LDAP hostis currently supported."""
Fixed. Thanks for your input

2023-01-19 04:13 UTC, jdkandersson approved these changes

2023-01-19 13:19 UTC, gregnebu commented on src/charm.py
> +            return
As discussed since my comment, we'll keep the implementation as it is (which means limiting to canonical LDAP only) but will work on integrator charms for LDAP / SAML and will refactor this part accordingly

2023-01-19 13:20 UTC, gregory-schiano commented on src/charm.py
> +            return
As discussed since my comment, we'll keep the implementation as it is (which means limiting to canonical LDAP only) but will work on integrator charms for LDAP / SAML and will refactor this part accordingly

2023-01-19 13:20 UTC, gregory-schiano approved these changes
LGTM

2023-01-19 13:29 UTC, merged