docs(ISD-145): Add Explanation
canonical/indico-operator pull request #195
Opened 2022-12-07 21:09 UTC by amandahla

To be merged/rebased: https://github.com/canonical/indico-operator/pull/188

2022-12-08 02:36 UTC, jdkandersson commented on docs/explanation/charm-architecture.md
> +In designing the charm, we've leveraged the [sidecar](https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/#example-1-sidecar-containers) pattern to allow us to run multiple con
In the documentation it can be helpful to avoid using `we` or `us` and try to make it neutral. E.g., `The charm design leverages the [sidecar](https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/#example-1-sidecar-containers) pattern ...`

2022-12-08 02:36 UTC, jdkandersson commented on docs/explanation/charm-architecture.md
> +Pebble is a lightweight, API-driven process supervisor that is responsible for configuring processes to run in a container and controlling those processes throughout the workload lifecycle.
Would it be worth including a link to more details on pebble?

2022-12-08 02:36 UTC, jdkandersson commented on docs/explanation/charm-architecture.md
> +This container runs the `nginx/nginx-prometheus-exporter` image.
Would it be worth including a link for more details on the container?

2022-12-08 02:36 UTC, jdkandersson commented on docs/explanation/charm-architecture.md
> +This container runs the `prom/statsd-exporter` image.
Similar question as the above, possibly a link to the container for more details?

2022-12-08 02:36 UTC, jdkandersson commented on docs/explanation/charm-architecture.md
> +# Charm Architecture
Would it be worth also discussing the architecture of the code inside the charm? E.g., key functions? I'm not sure what the answer is, something to consider

2022-12-08 13:10 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +In designing the charm, we've leveraged the [sidecar](https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/#example-1-sidecar-containers) pattern to allow us to run multiple con
I had the same idea and it was really bothering me but in the end, decided to left it after reading the [Google Developer Documentation Style Guide](https://developers.google.com/style/pronouns#personal-pronouns).
In the sense that "we" means "Canonical" and this paragraph tries to justify why the sidecar design pattern was chosen.
But your suggestion looks good too, I'll change it just in case to keep the neutral form.

2022-12-08 13:28 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +Pebble is a lightweight, API-driven process supervisor that is responsible for configuring processes to run in a container and controlling those processes throughout the workload lifecycle.
I was afraid that repeating links could "pollute" the reading. Actually, I'm worried that I already added too many. Usually, I create a link only at the first occurrence of the word. Do you think would be better to put in all of them?
I didn't find a guideline in Diátaxis but Google has even a term for that: "Link fatigue". :open_mouth: 
"To avoid link fatigue, don't provide duplicate links to the same document within a given page. "

2022-12-08 13:30 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +This container runs the `nginx/nginx-prometheus-exporter` image.
Same comment about link fatigue. One link was added at the beginning here:
https://github.com/canonical/indico-operator/blob/c31d156b95feff1b23912ce00251a7e21ad15e24/docs/explanation/charm-architecture.md?plain=1#L14

2022-12-08 13:31 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +This container runs the `prom/statsd-exporter` image.
Same thing as above. Here the first occurrence of the link:
https://github.com/canonical/indico-operator/blob/c31d156b95feff1b23912ce00251a7e21ad15e24/docs/explanation/charm-architecture.md?plain=1#L15

2022-12-08 13:34 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +# Charm Architecture
It's very tempting to do that but I think would be out of the scope of the "Explanation" concept. What do you think?
From [Diátaxis](https://diataxis.fr/explanation/):

> It’s not concerned with what the user might be doing, like tutorials and how-to guides. It’s not a close-up view of the machinery, like reference material. It’s documentation that approaches a topic from a higher perspective, and from different angles.

2022-12-09 01:01 UTC, jdkandersson commented on docs/explanation/charm-architecture.md
> +Pebble is a lightweight, API-driven process supervisor that is responsible for configuring processes to run in a container and controlling those processes throughout the workload lifecycle.
Yeh duplicate links are unnecessary. Although making words clickable multiple times can be helpful so the reader doesn't have to find the first reference. Up to you

2022-12-09 01:02 UTC, jdkandersson commented on docs/explanation/charm-architecture.md
> +# Charm Architecture
It is a judgement call, the code architecture could still be discussed at a higher level

2022-12-09 01:04 UTC, jdkandersson approved these changes, later dismissed

2022-12-09 09:46 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +Indico is a Flask application which means a [WSGI](https://wsgi.readthedocs.io/en/latest/what.html) application. A WSGI server is used to run it and uWSGI is the most popular one.
I'd rephrase this to something simpler like:
Indico is a Flask run by the [WSGI](https://wsgi.readthedocs.io/en/latest/what.html) server, one of the most popular servers for these applications.

2022-12-09 09:47 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +The Celery is used to process tasks created by the Indico application such as sending e-mails, survey notifications, event reminders, etc.
to process tasks asynchronously

2022-12-09 09:48 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +### PostgreSQL
I miss COS here

2022-12-09 09:48 UTC, arturo-seijas reviewed
Some comments inline

2022-12-09 12:56 UTC, arturo-seijas reviewed
I'm wondering what will be the behaviour if the current docs are not defined as source. Will they be deleted? Maybe we should copy all of those that are up to date.

2022-12-09 13:03 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +Indico is a Flask application which means a [WSGI](https://wsgi.readthedocs.io/en/latest/what.html) application. A WSGI server is used to run it and uWSGI is the most popular one.
Done!

2022-12-09 13:15 UTC, merkata approved these changes, later dismissed
Solid foundation, I like it!

2022-12-09 13:16 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +Indico is a Flask application which means a [WSGI](https://wsgi.readthedocs.io/en/latest/what.html) application. A WSGI server is used to run it and uWSGI is the most popular one.
Still don't see it

2022-12-09 13:28 UTC, merkata commented on docs/explanation/charm-architecture.md
> +The Celery is used to process tasks created by the Indico application such as sending e-mails, survey notifications, event reminders, etc.
It's async, you have to await for it...

2022-12-09 13:50 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +### Redis
There are two redis instances that are deployed with different purposes: as cache and as message broker. The later is not mentioned

2022-12-09 13:50 UTC, arturo-seijas requested changes
I miss some things, but it looks great overall

2022-12-09 14:07 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
>  The workload that this container is running is defined in the [indico dockerfile in the charm repository](https://github.com/canonical/indico-operator/blob/main/indico.Dockerfile).
You might want to capitalize `indico`here

2022-12-09 14:07 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +The uWSGI server is started in HTTP mode (port `8081`) serving Indico Application so NGINX can forward non-static traffic to it.
You might want to capitalize `indico` here

2022-12-09 14:08 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
>  The workload that this container is running is defined in the [indico dockerfile in the charm repository](https://github.com/canonical/indico-operator/blob/main/indico.Dockerfile).
You might want to capitalize indico here

2022-12-09 14:18 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +1. [<container name>_pebble_ready](https://juju.is/docs/sdk/container-name-pebble-ready-event): fired on Kubernetes charms when the requested container is ready. Action: wait for the integrations, an
Some of the sentences after `Action:` are capitalized, some aren't

2022-12-09 14:19 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +4. [refresh_external_resources_action](https://charmhub.io/indico/actions): fired when refresh-external-resources action is requested. Action: Pull changes from the customization repository, reload u
I'd go with `executed` instead of `requested`

2022-12-09 14:20 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +# Charm Architecture
I'll add something small to give an overview so.

2022-12-09 14:20 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +Indico is a Flask application which means a [WSGI](https://wsgi.readthedocs.io/en/latest/what.html) application. A WSGI server is used to run it and uWSGI is the most popular one.
Sorry, still working, will be available in my next commit.

2022-12-09 14:33 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +### PostgreSQL
I've added something for discourse, maybe you can leverage it :) https://github.com/canonical/discourse-k8s-operator/pull/21/files#diff-a91dcce1a3887d78aa883261a42dead6b363d5d3bc06e3b8838adbb16719ae19

2022-12-09 14:45 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +4. [refresh_external_resources_action](https://charmhub.io/indico/actions): fired when refresh-external-resources action is requested. Action: Pull changes from the customization repository, reload u
Done

2022-12-09 14:45 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +1. [<container name>_pebble_ready](https://juju.is/docs/sdk/container-name-pebble-ready-event): fired on Kubernetes charms when the requested container is ready. Action: wait for the integrations, an
I didn't found but just in case change the Action to a new line, to be more visible.

2022-12-09 14:45 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +5. [master_changed](https://github.com/canonical/ops-lib-pgsql): PostgreSQLClient custom event for when the connection details to the master database on this relation change. Action: Update the datab
Added.

2022-12-09 14:45 UTC, amandahla commented on docs/explanation/charm-architecture.md
>  The workload that this container is running is defined in the [indico dockerfile in the charm repository](https://github.com/canonical/indico-operator/blob/main/indico.Dockerfile).
Good catch

2022-12-09 14:47 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +### Redis
Thanks!

2022-12-09 14:50 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +## Code Overview
Why is this section empty?

2022-12-09 14:52 UTC, arturo-seijas commented on docs/explanation/charm-architecture.md
> +The `__init__` method guarantees that the charm observes all events relevant to its operation and handles them.
The `__init__` method guarantees that the charm observes and handles all events relevant to its operation.

seems simpler to me

2022-12-09 14:57 UTC, arturo-seijas reviewed
Are you planning to add the workflow changes to publish the code?

2022-12-09 15:21 UTC, amandahla commented
> Are you planning to add the workflow changes to publish the code?

There is a draft-publish-docs action already set in test_and_publish_charm. Would that be enough?

2022-12-09 15:26 UTC, amandahla commented on docs/explanation/charm-architecture.md
> +The `__init__` method guarantees that the charm observes all events relevant to its operation and handles them.
(I answered that and then it counted as a review so I deleted it, anyway...)
I think would "overlap" the Juju Doc so keeped it only with the necessary to understand (in a very general way) what the charm does.

2022-12-09 15:28 UTC, arturo-seijas approved these changes
LGTM

2022-12-09 15:36 UTC, arturo-seijas commented
> > Are you planning to add the workflow changes to publish the code?
> 
> There is a draft-publish-docs action already set in test_and_publish_charm. Would that be enough?

Yes, sorry. My mistake

2022-12-09 16:17 UTC, weiiwang01 approved these changes

2022-12-09 16:37 UTC, merged