Load tests
canonical/indico-operator pull request #208
Opened 2023-01-06 10:34 UTC by arturo-seijas

2023-01-06 10:45 UTC, gtrkiller submitted a review, later dismissed
LGTM

2023-01-12 11:48 UTC, merkata reviewed
Looks really good so far, solid foundation! :)

2023-01-16 11:26 UTC, nrobinaubertin requested changes

2023-01-16 11:26 UTC, nrobinaubertin commented on .github/workflows/load_test.yaml
> +    - cron: "0 12 * * 0"
I'm not sure to understand the intent, could you add a short explanation for the scheduling ?

2023-01-16 11:26 UTC, nrobinaubertin commented on tests/conftest.py
> +"""Fixtures for WordPress charm tests."""
s/Wordpress/Indico-operator

2023-01-16 11:28 UTC, arturo-seijas commented on .github/workflows/load_test.yaml
> +    - cron: "0 12 * * 0"
Does this suffice?

2023-01-16 11:30 UTC, weiiwang01 commented on .github/workflows/integration_test.yaml
> +    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@load-tests
I think it can wait until the `load-tests` branch merged into the `main` branch.

2023-01-16 11:30 UTC, weiiwang01 commented on tests/integration/conftest.py
> +# pylint:disable=redefined-outer-name
This can be avoided by naming the fixture function to `*_fixture` and using the `name` argument in fixture decorator.

```python3
@fixture(scope="module", name="metadata")
def metadata_fixture():
    """Provides charm metadata."""
    yield yaml.safe_load(Path("./metadata.yaml").read_text("utf-8"))
```

2023-01-16 11:48 UTC, arturo-seijas commented on tests/integration/conftest.py
> +# pylint:disable=redefined-outer-name
Thanks

2023-01-16 12:41 UTC, amandahla commented on .github/workflows/load_test.yaml
> +      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
Would it be worth bootstrapping Indico before running the test?

2023-01-16 12:51 UTC, arturo-seijas commented on .github/workflows/load_test.yaml
> +      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
This is just a dummy test but yes, this should be done when adding the proper tests

2023-01-16 13:28 UTC, nrobinaubertin commented on .github/workflows/load_test.yaml
> +    - cron: "0 12 * * 0"
If we want to avoid running a workflow, is it a possibility to avoid running it on commit that have a keyword (like `wf:no-load-test`) ?

2023-01-16 13:30 UTC, arturo-seijas commented on .github/workflows/load_test.yaml
> +    - cron: "0 12 * * 0"
Why would be want a mechanism to bypass the test?

2023-01-16 13:39 UTC, nrobinaubertin commented on .github/workflows/load_test.yaml
> +    - cron: "0 12 * * 0"
If we are changing a minor thing, or something that would not impact load tests, this would avoid the waiting time (and spare some resources). But I agree that it's out of scope and optional

2023-01-16 13:51 UTC, arturo-seijas commented on .github/workflows/load_test.yaml
> +    - cron: "0 12 * * 0"
It feels like over optimization. The compute resources are free (at least for now)

2023-01-16 14:50 UTC, nrobinaubertin approved these changes

2023-01-16 15:28 UTC, gtrkiller approved these changes
LGTM

2023-01-16 15:38 UTC, weiiwang01 approved these changes

2023-01-16 15:39 UTC, merged