WIP - test(ISD-374): Add OWASP Zap test
canonical/indico-operator pull request #210
Opened 2023-01-12 18:58 UTC by amandahla

To be merged only after https://github.com/canonical/operator-workflows/pull/70

Add OWASP Zap test after bootstraping Indico application.

2023-01-13 13:44 UTC, arturo-seijas submitted a review, later dismissed
LGTM

2023-01-15 23:53 UTC, jdkandersson reviewed
Thanks for adding all that documentation!

2023-01-15 23:53 UTC, jdkandersson commented on src/charm.py
> +        self.db = pgsql.PostgreSQLClient(self, "db")  # pylint: disable=C0103
What is the reason for the disable here please?

2023-01-15 23:53 UTC, jdkandersson commented on tests/integration/conftest.py
> +):  # pylint:disable=R0913
What is the reason for disable this here please?

2023-01-15 23:53 UTC, jdkandersson commented on tests/zap/add_header_request.py
> +    for h in list(headers):
Should we call the variable `header`? `h` could mean a lot of things

2023-01-15 23:53 UTC, jdkandersson commented on tests/zap/add_header_request.py
> +headers = dict({"Host": "indico.local"})
Would it be worth making this a tuple with 2 element tuples for each header name and value? and then it can be a constant? And the arguments to `.setHeader` would just be a `*` on the tuple with the header

2023-01-15 23:53 UTC, jdkandersson commented on tests/zap/add_header_request.py
> +def sendingRequest(msg, initiator, helper):  # noqa: N802
What is the reason for this naming convention please?

2023-01-15 23:53 UTC, jdkandersson commented on tests/zap/hook.py
> +    print(
Should we use `logging` here? Similar question for the remaining `print` statements

2023-01-15 23:53 UTC, jdkandersson commented on tox.ini
> +    pytest -v --tb native --ignore={[vars]tst_path}unit --log-cli-level=INFO -s {posargs}
Final new line?

2023-01-16 13:51 UTC, amandahla commented on tests/integration/conftest.py
> +):  # pylint:disable=R0913
"R0913: Too many arguments (6/5) (too-many-arguments)"
I didn't test but there is an option to change that: "max-args".

2023-01-16 13:59 UTC, amandahla commented on tests/zap/add_header_request.py
> +headers = dict({"Host": "indico.local"})
To be honest, I wrote like that because of this [example](https://github.com/zaproxy/community-scripts/blob/main/httpsender/add_header_request.py).

Now that you mentioned it and since it's only one header, we could just set it like this:
"msg.getRequestHeader().setHeader("Host", "indico.local)"

What do you think?

2023-01-16 14:03 UTC, amandahla commented on tests/zap/add_header_request.py
> +def sendingRequest(msg, initiator, helper):  # noqa: N802
This is defined and expected by ZAP tool. The template:
https://github.com/zaproxy/zap-extensions/blob/main/addOns/jython/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSender%20default%20template.py

2023-01-16 14:05 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +      zap-before-command: "curl -H \"Host: indico.local\" $ZAP_TARGET:8080/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.c
Order it alphabeticaly ?

2023-01-16 14:05 UTC, gregory-schiano commented on tests/integration/conftest.py
> +):  # pylint:disable=R0913
Could it be interesting to make a fixture that will return the 3 images in a dict ?

2023-01-16 14:36 UTC, amandahla commented on tests/zap/add_header_request.py
> +    for h in list(headers):
Removed the for as suggested in the next answer.

2023-01-16 17:02 UTC, arturo-seijas requested changes
There're lots of changes related to linting issues that should be solved already in main. Can you merge/rebase?

2023-01-16 17:15 UTC, amandahla commented on tests/conftest.py
> +"""Fixtures for WordPress charm tests."""
Merged.

2023-01-16 17:16 UTC, amandahla commented on tests/integration/conftest.py
> +):  # pylint:disable=R0913
Good idea!

2023-01-16 20:22 UTC, merkata commented
I don't know why Github shows all checks as passed, that's confusing, the actual run is in the integration tests and they are currently failing:

```text
[Invalid workflow file: .github/workflows/integration_test.yaml#L17](https://github.com/canonical/indico-operator/actions/runs/3932624507/workflow)
The workflow is not valid. .github/workflows/integration_test.yaml (Line: 17, Col: 20): Invalid input, zap-options is not defined in the referenced workflow.
```
Can you have a look @amandahla?

2023-01-16 20:27 UTC, amandahla commented
> I don't know why Github shows all checks as passed, that's confusing, the actual run is in the integration tests and they are currently failing:
> 
> ```
> [Invalid workflow file: .github/workflows/integration_test.yaml#L17](https://github.com/canonical/indico-operator/actions/runs/3932624507/workflow)
> The workflow is not valid. .github/workflows/integration_test.yaml (Line: 17, Col: 20): Invalid input, zap-options is not defined in the referenced workflow.
> ```
> 
> Can you have a look @amandahla?

Thanks for pointing that out! Fixed.

2023-01-17 00:30 UTC, jdkandersson commented on src/charm.py
> +        self.db = pgsql.PostgreSQLClient(self, "db")  # pylint: disable=C0103
I think `pylint` lets you configure `# pylint: disable=invalid-name` which means it is easier to know what the issue is. Would it be worth adding a comment explaining why this rule should be disabled?

2023-01-17 02:31 UTC, jdkandersson commented on tests/zap/add_header_request.py
> +headers = dict({"Host": "indico.local"})
Sounds reasonable too

2023-01-17 02:33 UTC, jdkandersson commented on tests/integration/conftest.py
> +    prometheus_exporter_images = {
could make this a `typing.NamedTuple` for easier auto-complete and to make sure that the dictionary can't be accidentally modified by other tests, what do you think?

2023-01-17 13:52 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +      zap-before-command: "curl -H \"Host: indico.local\" $ZAP_TARGET:8080/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.c
Can you execute this against the ingress instead? It should be available in localhost:80

2023-01-17 13:52 UTC, arturo-seijas commented on .github/workflows/integration_test.yaml
> +      zap-target-port: 8080
Same here, I guess

2023-01-17 14:40 UTC, amandahla commented on tests/integration/conftest.py
> +    prometheus_exporter_images = {
It's a good point but I left it as a dict because the only place that uses this is in the contest file itself in the app method as keys to "resources" dict. So returning a dict is an easier way to update this var.

What do you think? Could you please give an example of how it would work with NamedTuple?


```
    resources = {
        "indico-image": pytestconfig.getoption("--indico-image"),
        "indico-nginx-image": pytestconfig.getoption("--indico-nginx-image"),
    }
    resources.update(prometheus_exporter_images)
```

2023-01-17 14:42 UTC, amandahla commented on .github/workflows/integration_test.yaml
> +      zap-before-command: "curl -H \"Host: indico.local\" $ZAP_TARGET:8080/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.c
Sure, fixed.

2023-01-18 14:37 UTC, arturo-seijas approved these changes, later dismissed
LGTM

2023-01-19 04:39 UTC, jdkandersson commented on .github/workflows/integration_test.yaml
> +    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@ISD-374-owasp-baseline
I'm guessing we won't merge until we can point this back to main?

2023-01-19 04:39 UTC, jdkandersson commented on tests/integration/conftest.py
> +    prometheus_exporter_images = {
It is probably ok on this case since it is configuration passed in as a dictionary

2023-01-19 04:39 UTC, jdkandersson commented on tests/zap/add_header_request.py
> +# pylint: disable=missing-module-docstring,invalid-name,unused-argument
The new guidance on disabling linting rules includes adding a comment above the disable line explaining why the rule is bing disabled, is that applicable here? https://github.com/canonical/is-charms-contributing-guide/blob/main/CONTRIBUTING.md#static-code-analysis

2023-01-19 04:39 UTC, jdkandersson commented on tests/zap/hook.py
> +# pylint: disable=missing-module-docstring,invalid-name,unused-argument
The new guidance on disabling linting rules includes adding a comment above the disable line explaining why the rule is bing disabled, is that applicable here? https://github.com/canonical/is-charms-contributing-guide/blob/main/CONTRIBUTING.md#static-code-analysis

2023-01-19 04:39 UTC, jdkandersson commented on tests/zap/hook.py
> +        target (string): Target being scanned
Would it be worth putting the type hints in the function signature instead?

2023-01-19 09:36 UTC, arturo-seijas approved these changes, later dismissed
LGTM

2023-01-19 10:56 UTC, gregory-schiano commented on .github/workflows/integration_test.yaml
> +      zap-before-command: "curl -H \"Host: indico.local\" http://localhost/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.c
I think Niels is doing something to use the CLI in non-interactive shell, could be interesting to sync with him and align the approach for the boostrap

2023-01-19 13:55 UTC, amandahla commented on .github/workflows/integration_test.yaml
> +      zap-before-command: "curl -H \"Host: indico.local\" http://localhost/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.c
@nrobinaubertin Is it possible to bootstrap Indico using CLI?

2023-01-19 16:47 UTC, amandahla commented on .github/workflows/integration_test.yaml
> +    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@ISD-374-owasp-baseline
Yes, I just did this change to confirm that the baseline scan would work. :)

2023-01-19 16:55 UTC, nrobinaubertin commented on .github/workflows/integration_test.yaml
> +      zap-before-command: "curl -H \"Host: indico.local\" http://localhost/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.c
Right now, I'm working on patching the indico CLI to be able to add users non-interactively. Adding a user will dismiss the bootstrapping form.  
Since I'm patching the CLI and using a custom container for that, I think Amanda's solution is best for this PR

2023-01-19 17:09 UTC, amandahla commented on .github/workflows/integration_test.yaml
> +      zap-before-command: "curl -H \"Host: indico.local\" http://localhost/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.c
Thanks!

2023-01-19 18:40 UTC, amandahla commented on tests/zap/hook.py
> +        target (string): Target being scanned
Pylance complains that ZAPv2 is not defined.

2023-01-20 04:09 UTC, jdkandersson commented on tests/zap/hook.py
> +        target (string): Target being scanned
Maybe it needs to be imported? Type hints can also be strings?

2023-01-20 08:57 UTC, arturo-seijas approved these changes, later dismissed
Nice!

2023-01-20 13:57 UTC, amandahla commented on tests/zap/hook.py
> +        target (string): Target being scanned
I didn't want to import ZAPv2 because it's a hook script and I didn't find a way to add the Type Hint without importing it :-(
For now, I'll leave it just as a docstring but if you have an example of how to do it, that would be great.

2023-01-20 14:00 UTC, arturo-seijas approved these changes
LGTM

2023-01-23 09:34 UTC, gregory-schiano approved these changes
LGTM

2023-01-23 12:39 UTC, merged