Enable s3 storage support
canonical/indico-operator pull request #23
Opened 2022-06-21 15:19 UTC by arturo-seijas

Also removes multi-stage build on the indico container

2022-06-21 16:02 UTC, mthaddon commented on indico.Dockerfile
> -
How come we're able to remove all of this? There's no mention of why this is possible in the PR description, would be good to add there in future (but just replying here this time is fine).

2022-06-21 16:09 UTC, arturo-seijas commented on config.yaml
> +  indico_extra_plugins:
We're planning on supporting plugins from 3rd parties that will probably require installing, therefore the prefix. Also, we might want to enable some plugins out of the box

2022-06-22 07:20 UTC, mthaddon commented on src/charm.py
> +            "INDICO_EXTRA_PLUGINS": self.config["indico_extra_plugins"],
I don't think silently ignoring incorrect plugin names is a good user experience. We should be setting the charm to a blocked status with a message that there are unrecognised plugins.

2022-06-22 07:48 UTC, arturo-seijas commented on indico.Dockerfile
> -
We're are not having a multistage build anymore for this container. The packages that were installed only to compile indico are now needed for activating the plugins

2022-06-22 11:48 UTC, mthaddon commented on indico.Dockerfile
> -
Can you include a note about this in the description?

2022-06-22 12:35 UTC, arturo-seijas commented on src/charm.py
> +            "INDICO_EXTRA_PLUGINS": self.config["indico_extra_plugins"],
We are going to need to test those one by one in case they need additional dependencies installed or more configuration. Maybe when can postpone this till we start implementing the specifics for the plugins, limiting it to the ones supported?

2022-06-23 14:35 UTC, arturo-seijas commented on src/charm.py
> +            "INDICO_EXTRA_PLUGINS": self.config["indico_extra_plugins"],
As agreed, we're removing that config option for now

2022-06-28 08:01 UTC, mthaddon requested changes
One minor comment on the description field.

2022-06-28 08:01 UTC, mthaddon commented on config.yaml
> +    description: Comma separated list of parameters to connect to the S3 as specified in https://github.com/indico/indico-plugins/blob/master/storage_s3/README.md#available-config-options
"Comma separated list of parameters to connect to the S3" should be "Comma separated list of parameters to connect to S3". Let's include an example here as well please.

2022-06-28 09:50 UTC, mthaddon approved these changes
LGTM, thx

2022-06-28 09:51 UTC, merged