Adding health checks
canonical/indico-operator pull request #27
Opened 2022-07-01 16:25 UTC by gtrkiller

Adding health checks for indico, indico-celery and indico-nginx containers.

2022-07-04 13:37 UTC, mthaddon requested changes
Can you update the integration tests to use the new checks? Also, I'm not sure the ports you mention here are right - I think the indico application itself listens on port 8081. And I'm not sure you can hit the celery broker URL directly as you're doing here. Adding functional checks will confirm.

2022-07-04 13:39 UTC, arturo-seijas commented
It'd be nice to add some integration tests.

2022-07-04 13:47 UTC, arturo-seijas requested changes

2022-07-04 13:47 UTC, arturo-seijas commented on src/charm.py
> +                    "indico-ready": {"override": "replace", "level": "ready", "tcp": {"port": 80}}
Is this the check for uwsgi? If I remember correctly, it is listening in port 8081. Could you double check?

2022-07-04 13:47 UTC, arturo-seijas commented on src/charm.py
> +                        "http": {"url": "http://localhost:8080"},
It'd be nice to configure a new endpoint that would return a 204 to avoid coupling the nginx container status check with the uwsgi status.
With the current configuration, requests to / will be forwarded to the uwsgi container, causing the checks to fail if the latter is not serving requests properly, potentially causing unnecessary restarts of the nginx conatiner.
It will also be a faster operation.

2022-07-04 13:47 UTC, arturo-seijas commented on src/charm.py
> +                        "http": {"url": indico_env_config["CELERY_BROKER"]},
Running `celery inspect ping` might be a more reliable approach. Have you considered it? https://stackoverflow.com/questions/40430543/healthcheck-of-a-docker-container-running-celery-tasks

2022-07-04 18:34 UTC, gtrkiller commented on src/charm.py
> +                        "http": {"url": indico_env_config["CELERY_BROKER"]},
Using ```celery inspect ping```did not work, I'm using that URL as a workaround for now.

2022-07-19 12:29 UTC, arturo-seijas requested changes

2022-07-20 07:13 UTC, mthaddon requested changes
Some comments inline. Also, are the changes to `indico.Dockerfile` expected?

2022-07-20 07:13 UTC, mthaddon commented on src/charm.py
> +                        "timeout": "19s",
Are these period and timeout values right, or were they set to that for testing?

2022-07-20 07:13 UTC, mthaddon commented on src/charm.py
> +                        "exec": {"command": "/usr/local/bin/indico celery inspect ping", "environment": indico_env_config,},
I'd find this slightly more readable if it were split onto different lines (assuming correct indentation):

```
"exec": {
    "command": "/usr/local/bin/indico celery inspect ping", 
    "environment": indico_env_config,
},
```

2022-07-20 07:13 UTC, mthaddon commented on tests/integration/test_charm.py
> +
Can you remove the blank lines here at the end of the file?

2022-07-20 07:57 UTC, arturo-seijas commented
Please, resolve conflicts. Also, can you run tox locally before resubmitting the PR?

2022-07-20 07:57 UTC, arturo-seijas requested changes

2022-07-20 07:57 UTC, arturo-seijas commented on indico.Dockerfile
> +COPY files/etc/indico/* /etc/
No need for the asterisk

2022-07-20 07:57 UTC, arturo-seijas commented on indico.Dockerfile
> +    && chmod 755 /srv/indico
There's a missing blank line at the end

2022-07-20 12:17 UTC, gtrkiller commented
> Please, resolve conflicts. Also, can you run tox locally before resubmitting the PR?

I have already did. 

> Some comments inline. Also, are the changes to `indico.Dockerfile` expected?

Yes, they are. I have to resolve the conflicts on he file, but the modifications here are one of the necessary fixes to have the checks working in the first place.

2022-07-20 13:21 UTC, gtrkiller commented
If I try to resolve the conflict by using what is in main, the indico image will break and integration tests will fail. I need my changes in the dockerfile to be preserved for this to work, but I don't know if that would break other features.

2022-07-20 15:14 UTC, arturo-seijas requested changes

2022-07-20 15:14 UTC, arturo-seijas commented on indico.Dockerfile
>      && chmod 755 /srv/indico
Still no new line at the end of the file

2022-07-20 15:14 UTC, arturo-seijas commented on indico.Dockerfile
> -    &&  echo "* * * * * git -C /srv/indico/custom pull" | crontab -u indico - \
Did you remove the cron set-up by accident?

2022-07-20 15:14 UTC, arturo-seijas commented on tests/integration/test_charm.py
> +            assert result.count("0/3") == 2
No new line at the end of the file

2022-07-20 15:20 UTC, gtrkiller commented on indico.Dockerfile
>      && chmod 755 /srv/indico
I did put a new line, don't know why is not appearing.

2022-07-20 15:45 UTC, arturo-seijas requested changes

2022-07-20 15:45 UTC, arturo-seijas commented on indico.Dockerfile
> +RUN ["/bin/bash", "-c", "mkdir -p --mode=775 /srv/indico/{etc,tmp,log,cache,archive,custom}"]
This command and the next one are already present in line 15

2022-07-21 08:42 UTC, arturo-seijas commented
/rebase

2022-07-21 08:46 UTC, arturo-seijas commented
LGTM

2022-07-21 08:46 UTC, arturo-seijas approved these changes

2022-07-21 13:19 UTC, arturo-seijas approved these changes

2022-07-21 13:38 UTC, mthaddon reviewed
Some comments inline. Looks very close now!

2022-07-21 14:20 UTC, arturo-seijas submitted a review, later dismissed

2022-07-21 14:45 UTC, mthaddon approved these changes
LGTM, thanks!

2022-07-21 14:51 UTC, arturo-seijas approved these changes

2022-07-21 15:32 UTC, merged