SSO support
canonical/indico-operator pull request #34
Opened 2022-07-12 14:33 UTC by arturo-seijas

2022-07-18 09:45 UTC, mthaddon requested changes
Some comments inline. I think there's a balance here between making things too complicated now to support a theoretical future where we support multiple providers, and allowing us to add those in the future without needing to make too invasive changes.

One other question - will this _force_ logins via the configured provider, or will users still be able to create local accounts (we'd very much prefer it to be forced)?

2022-07-18 09:45 UTC, mthaddon commented on src/charm.py
> +        )
This function currently only checks if the saml_target_url is valid. I think we should either change this to be specifically about the saml config (`is_saml_target_url_valid`) or update it to be extendable to other config options in the future (likely by passing the message to block on).

2022-07-18 09:45 UTC, mthaddon commented on src/charm.py
> +UBUNTU_SAML_URL = "https://login.ubuntu.com/saml/"
This is a simple string variable currently, but if we want to support other providers in the future we'd need different variables for each.

2022-07-18 09:45 UTC, mthaddon commented on src/charm.py
> +            }
How would these data structures support other providers in the future? Would we set different `auth_providers` and `identity_providers` variables based on which provider(s) the user wanted to support? Do we expect to only ever support one provider, or to support multiple providers?

2022-07-18 10:24 UTC, arturo-seijas commented on src/charm.py
> +UBUNTU_SAML_URL = "https://login.ubuntu.com/saml/"
Yes, but I think is good enough for now. YAGNI maybe?

2022-07-18 10:26 UTC, arturo-seijas commented on src/charm.py
> +        )
Changed

2022-07-18 10:29 UTC, arturo-seijas commented
> Some comments inline. I think there's a balance here between making things too complicated now to support a theoretical future where we support multiple providers, and allowing us to add those in the future without needing to make too invasive changes.
> 
> One other question - will this _force_ logins via the configured provider, or will users still be able to create local accounts (we'd very much prefer it to be forced)?

An account will be created inside Indico and will be linked to the auth provider. Unfortunately, Indicoo accounts require both name and surname and our SSO service is storing that as a single value, so a little manual set up of the Indico account will be required. When logged in, a prepopulated form will appear to the user to complete the Indico account creation and once that is set up, the existence of this local account will be transparent to the user

2022-07-19 10:40 UTC, mthaddon approved these changes
LGTM

2022-07-19 10:55 UTC, merged