add high level development instructions
canonical/indico-operator pull request #53
Opened 2022-08-04 04:21 UTC by jdkandersson

2022-08-04 04:45 UTC, jdkandersson commented
Just found some more documentation I want to add, please hold review.

2022-08-04 05:19 UTC, jdkandersson commented
Alright, good for review now

2022-08-08 07:28 UTC, mthaddon commented
I think this is already covered by https://charmhub.io/indico/docs/contributing - can you take a look and confirm? The nature of documentation like this is still something we're in discussions with the documentation team about, but our current understanding is that this kind of content should be covered in the discourse-based detailed documentation that's rendered on charmhub.

2022-08-08 07:36 UTC, jdkandersson commented
> I think this is already covered by https://charmhub.io/indico/docs/contributing - can you take a look and confirm? The nature of documentation like this is still something we're in discussions with the documentation team about, but our current understanding is that this kind of content should be covered in the discourse-based detailed documentation that's rendered on charmhub.

Ah I see, do you think it is worth linking to the charmhub developer docs from the README file? The `juju deploy ./indico-operator_ubuntu-20.04-amd64.charm` command on charmhub is missing the resources (which it says in the comment above it as well), how do updates to that documentation work? I'm happy to add that part. The charmhub docs also seem to be missing the instructions for building the Docker images and how to get them into microk8s from Docker

2022-08-08 08:56 UTC, arturo-seijas requested changes

2022-08-08 08:56 UTC, arturo-seijas commented on .dockerignore
> +# Ignore everything
I think It'd be a good idea to split this dockerignore changes to another PR. I don't think they match the PR scope and they affect the build process.

2022-08-09 07:09 UTC, mthaddon commented
> Ah I see, do you think it is worth linking to the charmhub developer docs from the README file? The `juju deploy ./indico-operator_ubuntu-20.04-amd64.charm` command on charmhub is missing the resources (which it says in the comment above it as well), how do updates to that documentation work? I'm happy to add that part. The charmhub docs also seem to be missing the instructions for building the Docker images and how to get them into microk8s from Docker

The readme does already link to that - `For further details, [see here](https://charmhub.io/indico/docs)`. I can explain how to edit the discourse docs when we catch up tomorrow.

2022-08-09 07:09 UTC, mthaddon commented on .dockerignore
> +# Ignore everything
I agree on this.

2022-08-10 08:38 UTC, mthaddon commented
Closing out this pull request as discussed with David - changes will be integrated into the discourse-based documentation.

2022-08-10 08:38 UTC, closed without merging