Add more unit tests covering the pgsql db relation part
canonical/indico-operator pull request #55
Opened 2022-08-05 12:26 UTC by weiiwang01

Unit tests for the PostgreSQL database are currently missing due to the `ops-lib-pgsql` lib needs hook-tools commands. 
Add the necessary patch to work around that and add some unit tests for the pgsql db relation.

2022-08-05 12:28 UTC, weiiwang01 commented
Bump up the overall test coverage to 90%

2022-08-08 09:18 UTC, arturo-seijas requested changes

2022-08-08 09:18 UTC, arturo-seijas commented on tests/unit/test_charm.py
> +        for extension in ["pg_trgm:public", "unaccent:public"]:
You're actually checking those extensions are enabled but, shouldn't those be the only ones enabled?

2022-08-08 09:18 UTC, arturo-seijas commented on tests/unit/test_charm.py
>          self.harness.charm._stored.db_uri = "db-uri"
Do we still need to manually set the db_uri attr in the stored state?

2022-08-08 09:54 UTC, weiiwang01 commented on tests/unit/test_charm.py
>          self.harness.charm._stored.db_uri = "db-uri"
Without modifications on other test cases: yes. I was avoiding changing currently existing test cases. How about we change that? I can update this PR to remove all the manual db_uri setting.

2022-08-08 10:07 UTC, weiiwang01 commented on tests/unit/test_charm.py
> +        for extension in ["pg_trgm:public", "unaccent:public"]:
Yes, I was just afraid that the order of extensions in the extension list string will change.

2022-08-08 10:23 UTC, arturo-seijas commented on tests/unit/test_charm.py
> +        for extension in ["pg_trgm:public", "unaccent:public"]:
How about converting the list to a set and compare:
`self.assertSetEqual({"pg_trgm:public", "unaccent:public"}, db_relation_data.get("extensions"), "database roles should be set after relation joined")`

2022-08-08 10:25 UTC, arturo-seijas commented on tests/unit/test_charm.py
>          self.harness.charm._stored.db_uri = "db-uri"
I think we can live it as it is for now and maybe tackle that in another PR in the future. Thx for the clarification

2022-08-08 10:34 UTC, weiiwang01 commented on tests/unit/test_charm.py
> +        for extension in ["pg_trgm:public", "unaccent:public"]:
Updated to check using set

2022-08-08 10:45 UTC, arturo-seijas commented
LGTM. Unfortunatelly, you'll have to rebase once the linting fix gets merged

2022-08-08 10:46 UTC, arturo-seijas submitted a review, later dismissed

2022-08-09 09:01 UTC, mthaddon reviewed
As discussed IRL, let's add `--fail-under=90` to the coverage command in tox.ini so we don't reduce coverage without making an explicit choice to do so from now onwards.

2022-08-09 09:47 UTC, mthaddon commented
Looks like you've got some lint failures there:
```
tests/unit/_patched_charm.py:4:1: D205 1 blank line required between summary line and description
tests/unit/_patched_charm.py:4:1: D415 First line should end with a period, question mark, or exclamation point
tests/unit/_patched_charm.py:6:100: W505 doc line too long (100 > 99 characters)
```

2022-08-09 09:49 UTC, weiiwang01 commented
> Looks like you've got some lint failures there:
> 
> ```
> tests/unit/_patched_charm.py:4:1: D205 1 blank line required between summary line and description
> tests/unit/_patched_charm.py:4:1: D415 First line should end with a period, question mark, or exclamation point
> tests/unit/_patched_charm.py:6:100: W505 doc line too long (100 > 99 characters)
> ```

Yes, the rules are very strict, checking right now

2022-08-09 10:27 UTC, arturo-seijas requested changes

2022-08-09 10:27 UTC, arturo-seijas commented on .github/workflows/on_pull_request.yaml
> +  coverage-report:
Would it we worth to execute this on merge? I think it would make sense to put it in the ci.yaml file instead.

2022-08-09 10:27 UTC, arturo-seijas commented on coverage.txt
> +coverage installed: attrs==22.1.0,coverage==6.4.3,iniconfig==1.1.1,ops==1.5.0,ops-lib-pgsql==1.4,packaging==21.3,pgconnstr==1.0.1,pluggy==1.0.0,py==1.11.0,pyparsing==3.0.9,pytest==7.1.2,PyYAML==6.0,t
You might have added this report here by mistake? Please, include it in the gitignore file

2022-08-09 11:16 UTC, weiiwang01 commented
Sorry about all the error messages, I have created a GitHub action using GitHub Script to add a comment about the test coverage status in evert pull request. Due to the Github repository permission issues, [this action](https://github.com/canonical/indico-operator/runs/7744634248?check_suite_focus=true) will not success unless it was merged into this repo's main branch. 

Please see this GitHub Action's result and check the comment message example in [my forked repo](https://github.com/weiiwang01/indico-operator/pull/1#issuecomment-1209239785).

2022-08-09 11:23 UTC, weiiwang01 commented on coverage.txt
> +coverage installed: attrs==22.1.0,coverage==6.4.3,iniconfig==1.1.1,ops==1.5.0,ops-lib-pgsql==1.4,packaging==21.3,pgconnstr==1.0.1,pluggy==1.0.0,py==1.11.0,pyparsing==3.0.9,pytest==7.1.2,PyYAML==6.0,t
Yes, I will remove that, thanks

2022-08-09 11:26 UTC, arturo-seijas commented
> Sorry about all the error messages, I have created a GitHub action using GitHub Script to add a comment about the test coverage status in evert pull request. Due to the Github repository permission issues, [this action](https://github.com/canonical/indico-operator/runs/7744634248?check_suite_focus=true) will not success unless it was merged into this repo's main branch.
> 
> Please see this GitHub Action's result and check the comment message example in [my forked repo](https://github.com/weiiwang01/indico-operator/pull/1#issuecomment-1209239785).

Are you sure PRs from a fork will work? Maybe we'd need to specify the permissions in the WF:
```
permissions:
      issues: write
```

2022-08-09 12:03 UTC, weiiwang01 commented
> > Sorry about all the error messages, I have created a GitHub action using GitHub Script to add a comment about the test coverage status in evert pull request. Due to the Github repository permission issues, [this action](https://github.com/canonical/indico-operator/runs/7744634248?check_suite_focus=true) will not success unless it was merged into this repo's main branch.
> > Please see this GitHub Action's result and check the comment message example in [my forked repo](https://github.com/weiiwang01/indico-operator/pull/1#issuecomment-1209239785).
> 
> Are you sure PRs from a fork will work? Maybe we'd need to specify the permissions in the WF:
> 
> ```
> permissions:
>       issues: write
> ```

I just did some experiments, it seems like the forked repository will not have write permission in anyway, so I think I will just scratch this feature.

2022-08-09 12:06 UTC, arturo-seijas commented
> > > Sorry about all the error messages, I have created a GitHub action using GitHub Script to add a comment about the test coverage status in evert pull request. Due to the Github repository permission issues, [this action](https://github.com/canonical/indico-operator/runs/7744634248?check_suite_focus=true) will not success unless it was merged into this repo's main branch.
> > > Please see this GitHub Action's result and check the comment message example in [my forked repo](https://github.com/weiiwang01/indico-operator/pull/1#issuecomment-1209239785).
> > 
> > 
> > Are you sure PRs from a fork will work? Maybe we'd need to specify the permissions in the WF:
> > ```
> > permissions:
> >       issues: write
> > ```
> 
> I just did some experiments, it seems like the forked repository will not have write permission in anyway, so I think I will just scratch this feature.

It would certainly be useful to post the cause of the PR breaking as a comment. Perhaps we can try in the near future if there's any way to do it

2022-08-09 12:16 UTC, weiiwang01 commented
> > > > Sorry about all the error messages, I have created a GitHub action using GitHub Script to add a comment about the test coverage status in evert pull request. Due to the Github repository permission issues, [this action](https://github.com/canonical/indico-operator/runs/7744634248?check_suite_focus=true) will not success unless it was merged into this repo's main branch.
> > > > Please see this GitHub Action's result and check the comment message example in [my forked repo](https://github.com/weiiwang01/indico-operator/pull/1#issuecomment-1209239785).
> > > 
> > > 
> > > Are you sure PRs from a fork will work? Maybe we'd need to specify the permissions in the WF:
> > > ```
> > > permissions:
> > >       issues: write
> > > ```
> > 
> > 
> > I just did some experiments, it seems like the forked repository will not have write permission in anyway, so I think I will just scratch this feature.
> 
> It would certainly be useful to post the cause of the PR breaking as a comment. Perhaps we can try in the near future if there's any way to do it

I think a bot / service account like [Juju bot](https://github.com/jujubot) can certainly do that, but I think that would be too complicated for today.

2022-08-09 13:04 UTC, arturo-seijas approved these changes
LGTM

2022-08-09 14:11 UTC, mthaddon approved these changes
LGTM too, thx!

2022-08-09 14:36 UTC, merged