Prevent GitHub actions that require Charmhub secret to run on a forked repo
canonical/indico-operator pull request #60
Opened 2022-08-11 09:06 UTC by weiiwang01

2022-08-11 10:06 UTC, arturo-seijas requested changes

2022-08-11 10:06 UTC, arturo-seijas commented on .github/workflows/on_push.yaml
> +    if: github.repository == 'canonical/indico-operator'
Can we disable the whole on push listener instead?

2022-08-11 10:21 UTC, mthaddon commented on .github/workflows/on_push.yaml
> +    if: github.repository == 'canonical/indico-operator'
I think you can reference `repository_owner` here, which might make this a little more portable (i.e. we could have `canonical` and reuse for other repos without needing a change.

2022-08-11 10:24 UTC, weiiwang01 commented on .github/workflows/on_push.yaml
> +    if: github.repository == 'canonical/indico-operator'
I don't think the push event filter can do filtering based on the owner, and there if statement can't apply to the entire workflow, only to jobs. `lib-check` job is the precondition of all the jobs that use the Charmhub token, disable this one will prevent all of them from running which leaves only test jobs.

2022-08-11 10:29 UTC, arturo-seijas commented on .github/workflows/on_push.yaml
> +    if: github.repository == 'canonical/indico-operator'
Thx for the clarification

2022-08-11 10:33 UTC, weiiwang01 commented on .github/workflows/on_push.yaml
> +    if: github.repository == 'canonical/indico-operator'
Good idea, updated, thanks

2022-08-11 11:19 UTC, mthaddon commented on .github/workflows/on_push.yaml
> +    if: github.repository_owner == 'canonical'
I think it'd be good to have a comment explaining either here or in the comment block towards the top of the file that we don't want charm publishing to happen on forked repos, and this will achieve this (in case we change the layout and to make it easier to understand the intent).

2022-08-12 06:04 UTC, weiiwang01 commented on .github/workflows/on_push.yaml
> +    if: github.repository_owner == 'canonical'
Good idea, add some comments, thx

2022-08-12 07:55 UTC, arturo-seijas approved these changes
LGTM

2022-08-12 09:27 UTC, mthaddon approved these changes
LGTM, thx

2022-08-12 09:27 UTC, merged