Create a new Github action to comment test coverage report on PR
canonical/indico-operator pull request #83
Opened 2022-08-25 10:33 UTC by weiiwang01

Add a new Github action to create a comment on each pull request with the test coverage report in it. Most of the workflow code is inspired by this [post](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) wroten by the Github security team.

Since only workflow completion can trigger another workflow, I created another workflow that’s only the unit tests to trigger the comment workflow instead of using the CI workflow as the trigger to shorten the feedback loop. So now we don’t need to wait till the CI workflow finishes to see the comment popping in the PR, which may take 10+ minutes. The only drawback is the unit tests are running twice, but the duration of the unit tests is about 10 seconds, which is acceptable to me.

Please check this [demo PR page](https://github.com/weiiwang01/indico-operator/pull/14) on my forked repository to see this new workflow in action.

2022-08-25 10:56 UTC, arturo-seijas commented
Nice work! I'm actually thinking if we can split the current CI workflow in integration tests + rest (linting, unit tests and coverage) and report also the linting and unit test errors. What do you think?

2022-08-25 10:57 UTC, arturo-seijas requested changes
Just a remark to extend the reported results

2022-08-25 11:20 UTC, weiiwang01 commented
> Nice work! I'm actually thinking if we can split the current CI workflow in integration tests + rest (linting, unit tests and coverage) and report also the linting and unit test errors. What do you think?

I was thinking about this too, but if we want to keep the dependency between unit tests and integration tests, that's only run the integration test when unit tests succeed. Things could be a little bit complicated since there's no direct way in Github action to implement dependency between workflows.

2022-08-25 11:25 UTC, arturo-seijas commented
> > Nice work! I'm actually thinking if we can split the current CI workflow in integration tests + rest (linting, unit tests and coverage) and report also the linting and unit test errors. What do you think?
> 
> I was thinking about this too, but if we want to keep the dependency between unit tests and integration tests, that's only run the integration test when unit tests succeed. Things could be a little bit complicated since there's no direct way in Github action to implement dependency between workflows.

Can't we add the linting step in the new unit_test.yaml file? We'd keep the dependency and maybe generate from there the proper artifacts to then report the status

2022-08-26 03:04 UTC, jdkandersson commented
> > > Nice work! I'm actually thinking if we can split the current CI workflow in integration tests + rest (linting, unit tests and coverage) and report also the linting and unit test errors. What do you think?
> > 
> > 
> > I was thinking about this too, but if we want to keep the dependency between unit tests and integration tests, that's only run the integration test when unit tests succeed. Things could be a little bit complicated since there's no direct way in Github action to implement dependency between workflows.
> 
> Can't we add the linting step in the new unit_test.yaml file? We'd keep the dependency and maybe generate from there the proper artifacts to then report the status

Another option could be to make it a custom GitHub action that can be run after the unit test (similar to, for example, `charmed-kubernetes/actions-operator`: https://github.com/charmed-kubernetes/actions-operator)

2022-08-26 03:14 UTC, jdkandersson commented on .github/workflows/unit_test.yaml
> +        if: always() && github.event_name == 'pull_request'
What does always do here? A naive read makes this sounds like the equivalent in Python of `if True and github.event_name == "pull_request"` which could be abbreviated to `if github.event_name == "pull_request"`, maybe `always()` has a different meaning here?

2022-08-26 03:14 UTC, jdkandersson commented on .github/workflows/unit_test.yaml
> +          tox -e coverage-report -q | sed -n '/___ summary ___/q;p' > ./coverage-report/coverage-report.txt
out of curiosity, what does sed do in this case please? Is it filtering something from the coverage report that `coverage` creates?

2022-08-26 03:14 UTC, jdkandersson commented on tox.ini
> +    coverage[toml]
Again out of curiosity, what does the `[toml]` do here please?

2022-08-26 03:21 UTC, weiiwang01 commented on .github/workflows/unit_test.yaml
> +        if: always() && github.event_name == 'pull_request'
The always is one of the [status check functions](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions) to test if the previous step succeeded. The `tox -e unit` step may fail due to test coverage being less than threshold or bug, but the test coverage report can still be generated in that case, so we want the test coverage report to be created no matter what the test result is.

2022-08-26 03:22 UTC, weiiwang01 commented on .github/workflows/unit_test.yaml
> +          tox -e coverage-report -q | sed -n '/___ summary ___/q;p' > ./coverage-report/coverage-report.txt
It was filtering some meaningless summary printed by `tox`.

2022-08-26 03:25 UTC, weiiwang01 commented on tox.ini
> +    coverage[toml]
[It is needed to read `pyproject.toml`](https://coverage.readthedocs.io/en/6.4.4/config.html?highlight=coverage[toml])

2022-08-26 03:26 UTC, jdkandersson commented on .github/workflows/unit_test.yaml
> +        if: always() && github.event_name == 'pull_request'
so what would happen if the statement was just `if: github.event_name == 'pull_request'`?

2022-08-26 03:36 UTC, weiiwang01 commented on .github/workflows/unit_test.yaml
> +        if: always() && github.event_name == 'pull_request'
If one unit test failed or if the test coverage dropped below 90%, there will be no test coverage report for you :)

2022-08-26 03:55 UTC, jdkandersson commented on .github/workflows/unit_test.yaml
> +        if: always() && github.event_name == 'pull_request'
It turns out that, if `always()` isn't added, GitHub adds the `success()` call which is why the `always()` call is required here

2022-08-26 09:10 UTC, arturo-seijas submitted a review, later dismissed
Looks good. Just some minor details

2022-08-26 09:10 UTC, arturo-seijas commented on .github/workflows/comment.yaml
> +            }
You're missing a new line at the end here

2022-08-26 09:10 UTC, arturo-seijas commented on .github/workflows/test.yaml
> +          path: report.json
You're missing a new line at the end here

2022-08-26 09:13 UTC, weiiwang01 commented
I added the lint check and unit test results in the comments, it will only show up if lint checks or unit tests failed.
Final results can been seen in the following four demo PR:

- [Good PR](https://github.com/weiiwang01/indico-operator/pull/51)
- [PR with failed unit tests](https://github.com/weiiwang01/indico-operator/pull/48)
- [PR with failed lint checks](https://github.com/weiiwang01/indico-operator/pull/49)
- [PR with both unit tests and lint checks failed](https://github.com/weiiwang01/indico-operator/pull/50)

Question: Can we break the dependency between unit test and integration test, that's run integration test no matter unit test success or not. In that case we don't need to run unit test twice and make the check section in PR cleaner. The only drawback is that it will be more wasteful of computing resources.

2022-08-26 09:31 UTC, weiiwang01 commented on .github/workflows/comment.yaml
> +            }
Fixed

2022-08-26 09:32 UTC, weiiwang01 commented on .github/workflows/test.yaml
> +          path: report.json
Fixed

2022-08-26 10:28 UTC, arturo-seijas commented
> I added the lint check and unit test results in the comments, it will only show up if lint checks or unit tests failed. Final results can been seen in the following four demo PR:
> 
> * [Good PR](https://github.com/weiiwang01/indico-operator/pull/51)
> * [PR with failed unit tests](https://github.com/weiiwang01/indico-operator/pull/48)
> * [PR with failed lint checks](https://github.com/weiiwang01/indico-operator/pull/49)
> * [PR with both unit tests and lint checks failed](https://github.com/weiiwang01/indico-operator/pull/50)
> 
> Question: Can we break the dependency between unit test and integration test, that's run integration test no matter unit test success or not. In that case we don't need to run unit test twice and make the check section in PR cleaner. The only drawback is that it will be more wasteful of computing resources.

I'm not sure I follow. I'm seeing the following workflow
![image](https://user-images.githubusercontent.com/102022572/186884344-5d38cd16-dfdf-4ca8-a1ca-9ef83372a26f.png)

It is my understanding that the jobs "lint" and "unit test" are already being executed as part of "unit test and lint report" and hence, duplicated, is that right? Why not removing those two?

2022-08-29 05:08 UTC, jdkandersson commented on .github/workflows/test.yaml
> +          import os
Do you think this would be better as a separate Python file that is called from CI versus in-line Python code?

2022-08-29 05:08 UTC, jdkandersson commented on .github/workflows/test.yaml
> +        run: tox -e lint,unit,coverage-report --result-json=test-result.json
would it be possible to have the `lint` and `unit-test` jobs run in a way where they generate the relevant JSON reports and make them available as artefacts that can then be used by this job to format the reports and publish them? That would eliminate the need for testing and linting to run potentially twice and also simplifies this job (this step wouldn't need to install and run tox at all)

2022-08-29 05:09 UTC, jdkandersson commented
Thanks, the comments are looking excellent! Looking forward to having this available on this and our other repos

2022-08-29 06:11 UTC, weiiwang01 commented on .github/workflows/test.yaml
> +          import os
Yes, I think that's doable.

2022-08-29 06:36 UTC, weiiwang01 commented on .github/workflows/test.yaml
> +        run: tox -e lint,unit,coverage-report --result-json=test-result.json
Or maybe we can use [job outputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) to pass test results between jobs. There's a 1MB limit but with `xz` that would be plenty for this application.

2022-08-29 06:37 UTC, jdkandersson commented on .github/workflows/test.yaml
> +        run: tox -e lint,unit,coverage-report --result-json=test-result.json
Sounds like that would work also

2022-08-29 08:21 UTC, weiiwang01 commented
Some additional improvements I made so far:

- Change the order of comments in PR. Now it will go with lint then unit test then test coverage
- Break the dependency between unit tests and integration tests. Now integration tests will run no matter what the unit test result is. This will help to remove duplicated unit test runs and make the checks section in PR clear.
- Use job output to pass test results between jobs, reducing the duplicated unit test runs in the "Test" workflow
- Move inline Python and JavaScript code to separate files, improving the readability and extensibility.

Test PRs with the latest workflow:

- [Good PR](https://github.com/weiiwang01/indico-operator/pull/91)
- [PR with failed lint checks](https://github.com/weiiwang01/indico-operator/pull/89)
- [PR with failed unit tests](https://github.com/weiiwang01/indico-operator/pull/88)
- [PR with both lint checks and unit tests failed](https://github.com/weiiwang01/indico-operator/pull/90)

2022-08-29 08:58 UTC, arturo-seijas requested changes

2022-08-29 08:58 UTC, arturo-seijas commented on .github/files/comment_pr.js
> +}
Missing line at the end of file

2022-08-29 10:10 UTC, weiiwang01 commented on .github/files/comment_pr.js
> +}
Fixed, thanks

2022-08-29 10:28 UTC, arturo-seijas approved these changes
LGTM

2022-08-29 12:40 UTC, mthaddon commented on .github/workflows/test.yaml
> +    if: always() && github.event_name == 'pull_request'
What's the `if: always()` bit here?

2022-08-29 14:25 UTC, weiiwang01 commented on .github/workflows/test.yaml
> +    if: always() && github.event_name == 'pull_request'
Since the `report` job needs the outputs from `lint-and-unit-test` job, `lint-and-unit-test` needs to be included in the `needs` section of the `report` job definition. But we still want to run `report` job even if the `lint-and-unit-test` failed, so we have to include an `always()` here or Github will insert a `success()` implicitly which will make the `report` job run only if `lint-and-unit-test` succeeded. See this document for more details: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-not-requiring-successful-dependent-jobs

2022-08-29 15:16 UTC, mthaddon approved these changes
LGTM, thx! Really looking forward to seeing this in action.

2022-08-30 00:55 UTC, jdkandersson approved these changes

2022-08-30 08:15 UTC, merged